spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 5000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 500
