spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: passwd
    url: jdbc:mariadb://127.0.0.1:3306
    hikari:
      connection-test-query: SELECT 1 FROM dual
      connection-timeout: 5000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 500
